name: CI

on: [push]

jobs:
  
  build:
    name: E2E Tests
    # This job runs on Linux
    runs-on: ubuntu-18.04
    container:
      image: l.gcr.io/google/bazel:3.5.0
    steps:
      - uses: actions/checkout@v2
      - name: git_cached_repository tests
        run: |
            make run-tests

            